INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Eau Gazeuse', '0.50', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sucre', '0.1', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Feuille Menthe', '0.45', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Citron Vert', '0.50', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Rhum', '3', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Café Grain', '0.50', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Eau', '1', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sirop de Grenadine', '0.5', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sirop de Menthe', '0.5', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sirop de Citron', '0.5', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sucre de Canne', '0.05', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Citron Jaune', '0.40', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Biere', '1.6', 'true', 'true');

INSERT INTO recipe(rec_nom) VALUES ('Mojito');
INSERT INTO recipe(rec_nom) VALUES ('Eau');
INSERT INTO recipe(rec_nom) VALUES ('Limonade');
INSERT INTO recipe(rec_nom) VALUES ('Diabolo Menthe');
INSERT INTO recipe(rec_nom) VALUES ('Diabolo Grenadine');
INSERT INTO recipe(rec_nom) VALUES ('Diabolo Citron');
INSERT INTO recipe(rec_nom) VALUES ('Biere');
INSERT INTO recipe(rec_nom) VALUES ('Café');
INSERT INTO recipe(rec_nom) VALUES ('Monaco');

INSERT INTO contains(ing_id, rec_id) VALUES ('1', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('3', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('4', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('5', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('11', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('7', '2');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '3');
INSERT INTO contains(ing_id, rec_id) VALUES ('2', '3');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '4');
INSERT INTO contains(ing_id, rec_id) VALUES ('9', '4');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '5');
INSERT INTO contains(ing_id, rec_id) VALUES ('8', '5');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '6');
INSERT INTO contains(ing_id, rec_id) VALUES ('10', '6');
INSERT INTO contains(ing_id, rec_id) VALUES ('12', '7');
INSERT INTO contains(ing_id, rec_id) VALUES ('13', '7');
INSERT INTO contains(ing_id, rec_id) VALUES ('2', '8');
INSERT INTO contains(ing_id, rec_id) VALUES ('6', '8');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '9');
INSERT INTO contains(ing_id, rec_id) VALUES ('8', '9');
INSERT INTO contains(ing_id, rec_id) VALUES ('12', '9');
INSERT INTO contains(ing_id, rec_id) VALUES ('13', '9');
