INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Eau Gazeuse', '0.20', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sucre', '0.02', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Feuille Menthe', '0.25', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Citron Vert', '0.50', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Rhum', '2', 'true');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Café Grain', '0.50', 'false', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_cold, ing_alcohol) VALUES ('Eau', '0.50', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sirop de Grenadine', '0.25', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sirop de Menthe', '0.25', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sirop de Citron', '0.25', 'false');
INSERT INTO ingredient(ing_nom, ing_prix, ing_alcohol) VALUES ('Sucre de Canne', '0.05', 'false');
INSERT INTO ingredient(ing_nom, ing_cold, ing_cold, ing_alcohol) VALUES ('Citron Jaune', '0.40', 'true', 'false');
INSERT INTO ingredient(ing_nom, ing_cold, ing_cold, ing_alcohol) VALUES ('Biere', '1', 'true', 'true');

INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Mojito', 'true', 'true');
INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Eau', 'true', 'false');
INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Limonade', 'true, 'false');
INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Diabolo Menthe', 'true', 'false');
INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Diabolo Grenadine', 'true', 'false');
INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Diabolo Citron', 'true', 'false');
INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Biere', 'true', 'true');
INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Café', 'false', 'false');
INSERT INTO recipe(rec_nom, rec_cold, rec_alcohol) VALUES ('Monaco', 'true', 'true');

INSERT INTO contains(ing_id, rec_id) VALUES ('1', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('3', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('4', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('5', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('11', '1');
INSERT INTO contains(ing_id, rec_id) VALUES ('7', '2');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '3');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '4');
INSERT INTO contains(ing_id, rec_id) VALUES ('9', '4');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '5');
INSERT INTO contains(ing_id, rec_id) VALUES ('8', '5');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '6');
INSERT INTO contains(ing_id, rec_id) VALUES ('10', '6');
INSERT INTO contains(ing_id, rec_id) VALUES ('12', '7');
INSERT INTO contains(ing_id, rec_id) VALUES ('13', '7');
INSERT INTO contains(ing_id, rec_id) VALUES ('2', '8');
INSERT INTO contains(ing_id, rec_id) VALUES ('6', '8');
INSERT INTO contains(ing_id, rec_id) VALUES ('1', '9');
INSERT INTO contains(ing_id, rec_id) VALUES ('8', '9');
INSERT INTO contains(ing_id, rec_id) VALUES ('12', '9');
INSERT INTO contains(ing_id, rec_id) VALUES ('13', '9');

